### ISSUE TITLE
Tasks for initial release (v0.0.1)

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rslib#3]
## Workflows and Architecture

```[tasklist]
### Tasks
- [x] Integrate Nx for dev
- [x] Auto update dependencies - use renovate and update partial dependencies manually
- [x] Add cspell check
- [x] Add Rslib README
- [x] Add Rslib Contribution Guide
- [x] Add more examples
- [x] Add LICENSE to npm packages
- [x] Testing workflow - ubuntu / Windows / macOS
- [x] Release workflow
- [x] Add Rslib to ecosystem-ci
- [x] Add Rslib to web-infra-QoS
```

## Documentation

```[tasklist]
### Tasks
- [x] Design a new logo
- [x] Add Rslib to [rsfamily-doc-ui](https://github.com/rspack-contrib/rsfamily-doc-ui) and update all Rstack docs
- [ ] Website initialization
- [ ] Website deploy workflow
```

## Features

```[tasklist]
### Tasks
- [x] CLI and load config architecture
- [x] Able to build decent Node.js package
```
